import type { LanguageAdapter, MethodCallOptions } from './types.js';
import type { NormalizedParam, NormalizedRequestBody, NormalizedSchema } from '../spec/types.js';
import { registerLanguage } from './registry.js';

/**
 * Adapter for Python SDKs generated by openapi-python-client.
 *
 * openapi-python-client produces a module-based API where each operation
 * is a separate module with sync/asyncio functions, rather than methods
 * on an API class. Usage pattern:
 *
 *   from package.api.tag_module import operation_module
 *   result = operation_module.sync(client=client, param=value)
 */

function toSnakeCase(str: string): string {
  return str
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .toLowerCase()
    .replace(/^_|_$/g, '');
}

function wrapOverrideForType(override: string, schema: NormalizedSchema): string {
  if (schema.type === 'string' && !(schema.format === 'date' || schema.format === 'date-time')) {
    return `"${override}"`;
  }
  return override;
}

function exampleValueForSchema(schema: NormalizedSchema, name: string): string {
  if (schema.enum && schema.enum.length > 0) {
    return `"${schema.enum[0]}"`;
  }
  if (schema.default != null) {
    return typeof schema.default === 'string' ? `"${schema.default}"` : String(schema.default);
  }
  switch (schema.type) {
    case 'string':
      if (schema.format === 'date' || schema.format === 'date-time') {
        return 'datetime.now()';
      }
      return `"${name}_value"`;
    case 'integer':
    case 'number':
      return '0';
    case 'boolean':
      return 'True';
    case 'object':
      if (schema.properties) {
        return buildObjectLiteral(schema, 0);
      }
      return '{}';
    case 'array':
      if (schema.items) {
        const itemValue = exampleValueForSchema(schema.items, 'item');
        return `[${itemValue}]`;
      }
      return '[]';
    default:
      return `"${name}_value"`;
  }
}

function mapPythonType(schema: NormalizedSchema): string {
  switch (schema.type) {
    case 'string':
      if (schema.format === 'date' || schema.format === 'date-time') {
        return 'datetime';
      }
      return 'str';
    case 'integer':
      return 'int';
    case 'number':
      return 'float';
    case 'boolean':
      return 'bool';
    case 'array':
      if (schema.items) {
        return `list[${mapPythonType(schema.items)}]`;
      }
      return 'list';
    case 'object':
      return 'dict';
    default:
      return 'object';
  }
}

function buildObjectLiteral(
  schema: NormalizedSchema,
  depth: number,
  valueOverrides?: Record<string, string>,
  schemaName?: string,
): string {
  const props = schema.properties ?? {};
  const required = schema.required ?? [];
  const indent = '    '.repeat(depth + 1);
  const closingIndent = depth > 0 ? '    '.repeat(depth) : '';

  const entries: string[] = [];
  for (const [propName, propSchema] of Object.entries(props)) {
    if (required.includes(propName)) {
      const override = valueOverrides?.[propName];
      const fieldName = toSnakeCase(propName);
      let value: string;
      if (override != null) {
        value = wrapOverrideForType(override, propSchema);
      } else if (propSchema.type === 'object' && propSchema.properties) {
        value = buildObjectLiteral(propSchema, depth + 1);
      } else {
        value = exampleValueForSchema(propSchema, propName);
      }
      entries.push(`${indent}${fieldName}=${value},`);
    }
  }

  if (entries.length === 0) {
    return schemaName ? `${schemaName}()` : '{}';
  }

  if (schemaName) {
    return `${schemaName}(\n` + entries.join('\n') + '\n' + `${closingIndent})`;
  }

  // Dict fallback: convert field=value to "field": value
  const dictEntries = entries.map((e) =>
    e.replace(/^(\s*)(\w+)=(.+),\s*$/, '$1"$2": $3,'),
  );
  return '{\n' + dictEntries.join('\n') + '\n' + `${closingIndent}}`;
}

const pythonOpcAdapter: LanguageAdapter = {
  id: 'python-opc',
  generatorNames: ['openapi-python-client'],
  codeBlockLang: 'python',

  toMethodName(operationId: string): string {
    return toSnakeCase(operationId);
  },

  toFileName(operationId: string): string {
    return toSnakeCase(operationId);
  },

  toTagDirectory(tag: string): string {
    return toSnakeCase(tag);
  },

  toApiClassName(tag: string): string {
    return toSnakeCase(tag);
  },

  mapType(schema: NormalizedSchema): string {
    return mapPythonType(schema);
  },

  exampleValue(param: NormalizedParam): string {
    if (param.example != null) {
      return typeof param.example === 'string' ? `"${param.example}"` : String(param.example);
    }
    return exampleValueForSchema(param.schema, param.name);
  },

  buildParamDeclaration(param: NormalizedParam, valueOverride?: string): string {
    const pyType = this.mapType(param.schema);
    const value = valueOverride != null
      ? wrapOverrideForType(valueOverride, param.schema)
      : this.exampleValue(param);
    return `${toSnakeCase(param.name)}: ${pyType} = ${value}`;
  },

  buildMethodCall(opts: MethodCallOptions): string {
    const { clientVar, methodName, args } = opts;
    // Convert positional args to keyword args, prepend client=clientVar
    const kwargParts = [`client=${clientVar}`];
    if (args) {
      for (const arg of args.split(', ').filter(Boolean)) {
        const snaked = toSnakeCase(arg);
        kwargParts.push(`${snaked}=${snaked}`);
      }
    }
    return `await ${methodName}.asyncio(${kwargParts.join(', ')})`;
  },

  buildBodyConstruction(body: NormalizedRequestBody, valueOverrides?: Record<string, string>): string {
    const literal = buildObjectLiteral(body.schema, 0, valueOverrides, body.schemaName);
    return `body = ${literal}`;
  },

  buildResultLine(call: string, _returnType: string | undefined): string {
    return `result = ${call}`;
  },
};

registerLanguage(pythonOpcAdapter);
